return {}

-- return {
-- 	{
-- 		"neovim/nvim-lspconfig",
-- 		opts = {
-- 			autoformat = false,
-- 		},
-- 	},
-- }

-- return {
--     {
--         "stevearc/conform.nvim",
--         enabled = false,
--         opts = {
--             format = {
--                 -- dry_run = true,
--             },
--             formatters_by_ft = {
--                 -- disable stylua
--                 -- lua = { "stylua" },
--                 fish = { "fish_indent" },
--                 sh = { "shfmt" },
--             },
--             -- format_on_save = function(bufnr)
--             --     if vim.b[bufnr].filetype == "lua" then
--             --         return
--             --     end
--             --     return { timeout_ms = 500, lsp_fallback = true }
--             -- end,
--         },
--     },
-- }
